# Generated by Django 5.2.3 on 2025-07-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_tenant_to_models'),
        ('tenants', '0002_tenantconfiguration_config_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['tenant'], name='api_itemven_tenant__819538_idx'),
        ),
    ]
