# Generated by Django 5.2.3 on 2025-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='config_type',
            field=models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Inteiro'), ('float', 'Número Decimal'), ('boolean', 'Verdadeiro/Falso'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20, verbose_name='Tipo da Configuração'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Marque se esta configuração contém informações sensíveis (será criptografada)', verbose_name='Informação Sensível'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permissões específicas do usuário em formato JSON', verbose_name='Permissões Específicas'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
